### ISSUE TITLE
Websocket Server with HTTPS callback is not working

### ISSUE THREAD

**Issue by Bogatinovski** [yjs/y-websocket#54]
**Describe the bug**
The HTTP callback is failing to execute. The server seems to be trying to call the method whenever there is a change of the text editor content, but it gives the following error message in the console: 
`Callback request error. Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:459:23)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'` 

**To Reproduce**
1. Go to https://github.com/BitPhinix/slate-yjs-example
2. Clone the repository locally
3. Run `npm install`
4. Modify the `start:server` command to `"set HOST=localhost&&set PORT=1234&&set CALLBACK_URL=https://localhost:5001/weatherforecast&&set CALLBACK_OBJECTS={\"prosemirror\":\"XmlFragment\"}&& npx y-websocket-server"`
5. Run `npm run start:server`

**Expected behavior**
I expect that the HTTP method will be called instead of getting that error message in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/7543902/108496946-17405c00-72ab-11eb-87de-4945b602f00e.png)

**Environment Information**
 - Chrome 88.0.4324.150 / Node.js v12.19.0
 - Yjs version: npm ls yjs

**Comment by Bogatinovski** [comment]
**The issue does not happen If I set the CALLBACK_URL to CALLBACK_URL=https://localhost:5001/weatherforecast**. Obviously the problem is with HTTPS. This is probably due to using self-issued certificates on localhost
