### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by meoyawn** [yjs/y-websocket#79]
**Checklist**

[x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**
I'm building a collaborative application https://arrowbox.co and I want people to share their documents in read-only mode

**Describe the solution you'd like**
Some way to open a WS connection in read-only mode. While still allowing write connections from different clients

**Describe alternatives you've considered**
Tried this solution https://github.com/stoplightio/y-websocket/pull/1/files but it failed with

```
const readItemContent = (decoder, info) => contentRefs[info & binary.BITS5](decoder);
                                                                           ^

TypeError: contentRefs[(info & binary.BITS5)] is not a function
    at readItemContent (file:///Users/adelnizamutdinov/Projects/diagrams/node_modules/yjs/dist/yjs.mjs:9426:76)
    at readClientsStructRefs (file:///Users/adelnizamutdinov/Projects/diagrams/node_modules/yjs/dist/yjs.mjs:1308:13)
    at file:///Users/adelnizamutdinov/Projects/diagrams/node_modules/yjs/dist/yjs.mjs:1535:16
    at transact (file:///Users/adelnizamutdinov/Projects/diagrams/node_modules/yjs/dist/yjs.mjs:3198:5)
    at readUpdateV2 (file:///Users/adelnizamutdinov/Projects/diagrams/node_modules/yjs/dist/yjs.mjs:1528:3)
    at readUpdate (file:///Users/adelnizamutdinov/Projects/diagrams/node_modules/yjs/dist/yjs.mjs:1607:58)
    at readSyncMessage (file:///Users/adelnizamutdinov/Projects/diagrams/back/dist/src/sync.js:82:17)
```

**Additional context**
Discussion https://discuss.yjs.dev/t/read-only-or-one-way-only-sync/135/9

**Comment by guiprav2** [comment]
@dmonad: Any reason not to pull this upstream? https://github.com/stoplightio/y-websocket/pull/1/files
